# Generated by Django 4.2.30 on 2026-09-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0003_recado_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recado',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='recados/'),
        ),
    ]
